Default: &defaults
  database: foo.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: foo_test.sqlite3
  <<: *defaults

Staging:
  database: foo_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: foo_production.sqlite3
  poolsize: 100
  <<: *defaults
